### ISSUE TITLE
Konfiguracja CI

### ISSUE THREAD

**Issue by mmateja** [mmateja/iosr-slideshows#3]

**Comment by mmateja** [comment]
Ja próbowałem zainstalować Stridera i poległem. Wywala się na instalacji przez npm'a.
Sami spróbujcie. W razie problemów trzeba szukać innych technologii (np Jenkins).

**Comment by d00d171** [comment]
To jak robimy? Jezeli nie przeszkadza ci ze apka będzie miała dostęp to dodaj ją do autoryzowanych i podeślij te klucze jakoś mailem, a w przeciwnym przypadku trzeba będzie założyć nowe konto projektowe.

**Comment by mmateja** [comment]
Ale to chyba nie jest konieczne. W [dokumentacji](https://github.com/Strider-CD/strider-github#required-configuration) jest napisane, że to jest wymagane tylko wtedy jeśli chcesz używać jakiegoś własnego adresu i portu.

>If you are running on localhost:3000 the default settings should work just fine.

Strider tylko śledzi jakąś gałąź w repozytorium, a do tego nie trzeba uprawnień.

Wolałbym nie dawać dostępu jakiejś dziwnej apce do wszystkich moich repozytoriów. :)

**Comment by d00d171** [comment]
Próbowałem bez ustawiania żadnych zmiennych środowiskowych na początku i
leciały błędy od razu. Spróbuje jeszcze raz a jak nic z tego nie będzie to
założę nowe konto na githubie i będziemy go najwyżej używać do tego
projektu, a przynajmniej do wrzucania kodu żeby już nie przenosić wiki itp.
9 kwi 2015 09:21 "Marek Mateja" <notifications@github.com> napisał(a):

**Comment by d00d171** [comment]
Postawiłem serwer na maszynie. Nie było konieczne używanie tych kluczy itp ale żeby się połączyć z repo trzeba być zalogowanym na konto właściciela, więc stworzyłem tymczasowo osobne konto. Później Marek będziesz musiał po prostu pierwszy raz się ty połączyć i będzie ok - skrypty itp się skopiuje.
Jak coś będziecie wrzucać na jutro to dajcie znać, tymczasowo to przeniose do tamtego repo a szczegóły ustalimy później.

Są dwa problemy z CI.
1. Nie buduje się automatycznie po commicie - webhook jest założony, wszystko powinno być ok, ale leci timeout, więc tymczasowo trzeba to robić ręcznie. Nie jestem pewien czy uda się to rozwiązać. Jeżeli nie to wg mnie nie jest dużym problemem żeby odpalać samemu.
2. Testy z karma udało mi się odpalić ale rezultaty się nie prezentują w buildzie - wygląda to jakby Phantom działał w jakimś innym terminalu ?? - pewnie da się to ogarnąć.
