### ISSUE TITLE
Specyfikacja REST API

### ISSUE THREAD

**Issue by mmateja** [mmateja/iosr-slideshows#6]
Spisać formalnie jak wyglądają endpointy (ścieżki, formaty JSONów).
Dostosować kod serwerowy do tych specyfikacji.

**Comment by mmateja** [comment]
Moje propozycje zmian:

* /slideshows - dorobiłbym to o czym mówiłem kiedyś, żeby w danych prezentacji był też link do zasobu   konkretnej prezentacji
  > [
  >   {
  >     "_id": "slideshowId",
  >     "url" : "/slideshows/7",
  >     "document-name": "Sample slideshow"
  >   }
  > ]

  wtedy się łatwiej z takiego API korzysta i można w razie czego zmienić te ścieżki na serwerze.

* Trzeba dorobić endpoint do tworzenia użytkowników

* Ja bym to przerobił tak, żeby był endpoint na cały plik prezentacji, bez rozdrabniania się na jakieś częśći - odczytujemy całość, zapisujemy całość.

**Comment by d00d171** [comment]
Ad 1. Jeżeli uważasz że będzie to dla ciebie wygodniejsze to nie ma problemu, można dodać coś takiego. 

Osobiście wydaje mi się że w niczym to nie pomoże, bo wg mnie będzie tak:
- pobierasz listę pokazów
- ktoś wybiera konkretny pokaz i chcesz pobrać jego szczegóły
- w tym celu wołasz metodę z sliServerService (podobną do deleteSlideshow ; jeszcze jej nie ma, ale powiedzmy ze będzie to getSlideshow (id ) ) - czyli musisz znać tylko id pokazu slajdów

Gdybyś chciał korzystać z urla to sam musiałbyś wołąć $http.get(url) - wtedy serwis nie ma sensu, a wg mnie jest wygodny, bo w nim byłyby zdefiniowane wszystkie możliwe operacje i od razu obsługa wyjątków w jednym miejscu a nie wszędzie gdzie będziesz korzystał z api restowego.
W serwisie myślałem obsłużyc promise związany z zawołaniem do $http i zwracać już promise przetworzony a nie surowy response http z headerami i body prosto z serwera, tak jak teraz jest to na szybkości zrobione. 

Powiedzmy że w kontrolerze używałoby się tego np. tak: 
sliServerService.getSlideshow( 1 )
.success ( function( slideshowJson ) {
   i tutaj slideshowJson to już faktycznie json który ma być
})
.error ( function(errorMessage) {
  tutaj od razu errorMessage - czyli info co nie tak do wyświetlenia dla usera gdzieś, zamiast jakiegoś         statusu http czy czegoś tam
});

Dodatkowo dzięki obsłudze wszystkich zawołań do serwera w jednym miejscu można np. zrobić mechanizm który w momencie zawołania pokazuje jakiś pasek postępy i wyszarza cały ekran a po otrzymaniu odpowiedzi go ukrywa.

Działałbyś na trochę wyższym poziomie abstrakcji.
Podsumowując: jak jesteś pewien że chcesz urle, to napisz - doda się, tylko daj znać jak będziemy z nich korzystać.

Ad 2. Jak tylko będzie wiadomo coś więcej o google oauth i tym co ma być trzymane to jak najbardziej

Ad 3. Odczyt całości już jest; 
Co do zapisu - endpoint "Utwórz pokaz slajdów".
Co do endpointa "Modyfikuj pokaz slajdów" - jeżeli podasz tam jsona zawierającego pełny obiekt json z nowym pokazem to stary zostanie w pełni zamieniony. To że w przypadku podania tylko części pól zamienione zostaną podane to jak dla mnie feature który nie musi zostać wykorzystany ;)
Endpointy z sekcji "Slajd" myślę że można dodać - jeżeli nie będą wykorzystywane to nie ma problemu, a mogą się okazać przydatne w przyszłości.

**Comment by d00d171** [comment]
*Dodatkowo, nie wiem gdzie to zamieścić ale do takich ładnych wyskakujących okienek czy dropdownów/przycisków proponuje wykorzystywać https://angular-ui.github.io/bootstrap/

**Comment by mmateja** [comment]
Póki co olejmy te linki, bo nie jest to jakieś konieczne.

Do obsługi RESTowego API jest w angularze moduł $resource, który stanowi abstrakcję $http i robi to samo.

Bootstrapa używam od samego początku. :)

**Comment by d00d171** [comment]
$resources wygląda elegancko. użyje tego w serwisie do tych nie-mockowanych
metod. Mocki w przyszłości myślałem żeby przerobić na tryb offline.
Jak będziesz określał strukturę tych obiektów content to  dodawaj
przykładowe w dbMockService.js i daj znać to będę od razu przenosił
schematy do serwera żebyśmy się nie blokowali.
16 kwi 2015 09:35 "Marek Mateja" <notifications@github.com> napisał(a):
